name: git-chglog-action
description: GitHub Action for git-chglog/git-chglog
author: "Hiroki Sakuraba"
inputs:
  repository:
    description: repository name
    required: true
outputs:
  changelog:
    description: Generated changelog
runs:
  using: docker
  image: Dockerfile
branding:
  icon: edit
  color: gray-dark
